server {
    listen       80;
    server_name  localhost;
    root         /usr/share/nginx/html;
    index        index.html;

    location /material/ {
        autoindex            on;
        autoindex_format     json;
        autoindex_localtime  on;
    }

    location / {
        try_files $uri $uri/ =404;
    }
}
